<?xml version="1.0" encoding="UTF-8"?>
<!--

    Copyright (c) 2025 Eurotech and/or its affiliates and others

    This program and the accompanying materials are made
    available under the terms of the Eclipse Public License 2.0
    which is available at https://www.eclipse.org/legal/epl-2.0/

    SPDX-License-Identifier: EPL-2.0

    Contributors:
     Eurotech

-->
<project xmlns="http://maven.apache.org/POM/4.0.0"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">

    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>org.eclipse.kura</groupId>
        <artifactId>kura-examples-distrib</artifactId>
        <version>6.0.0-SNAPSHOT</version>
    </parent>

    <artifactId>kura-camel-examples-distrib</artifactId>
    <packaging>pom</packaging>

    <dependencies>
        <dependency>
            <groupId>org.eclipse.kura</groupId>
            <artifactId>org.eclipse.kura.example.camel.aggregation</artifactId>
        </dependency>
        <dependency>
            <groupId>org.eclipse.kura</groupId>
            <artifactId>org.eclipse.kura.example.camel.publisher</artifactId>
        </dependency>
        <dependency>
            <groupId>org.eclipse.kura</groupId>
            <artifactId>org.eclipse.kura.example.camel.quickstart</artifactId>
        </dependency>
    </dependencies>

    <properties>
        <addon.installation.dir>/opt/eclipse/kura/plugins/6s</addon.installation.dir>
        <jar.name>kura-camel-example.bundle-${project.version}.jar</jar.name>
        <deb.architecture>all</deb.architecture>
        <package.name>kura-camel-example</package.name>
        <kura.repo.distribution>kura-6</kura.repo.distribution>
        <kura.repo.module>base</kura.repo.module>
        <summary>Eclipse Kura Addon for Camel</summary>
        <long.description>Examples of Camel addons for the Eclipse Kura Framework.</long.description>
    </properties>

    <build>
        <plugins>
            <plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>build-helper-maven-plugin</artifactId>
            </plugin>
            <plugin>
                <groupId>io.github.git-commit-id</groupId>
                <artifactId>git-commit-id-maven-plugin</artifactId>
            </plugin>
            <plugin>
                <artifactId>maven-dependency-plugin</artifactId>
            </plugin>
            <plugin>
                <groupId>org.vafer</groupId>
                <artifactId>jdeb</artifactId>
            </plugin>
        </plugins>
    </build>

</project>