<?xml version="1.0" encoding="UTF-8"?>
<!--

    Copyright (c) 2025 Eurotech and/or its affiliates and others

    This program and the accompanying materials are made
    available under the terms of the Eclipse Public License 2.0
    which is available at https://www.eclipse.org/legal/epl-2.0/

    SPDX-License-Identifier: EPL-2.0

    Contributors:
     Eurotech

-->
<project xmlns="http://maven.apache.org/POM/4.0.0"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">

    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>org.eclipse.kura</groupId>
        <artifactId>kura-examples-distrib</artifactId>
        <version>6.0.0-SNAPSHOT</version>
    </parent>

    <artifactId>kura-heater-examples-distrib</artifactId>
    <packaging>pom</packaging>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>org.eclipse.kura</groupId>
                <artifactId>kura-examples-bom</artifactId>
                <version>6.0.0-SNAPSHOT</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>

    <dependencies>
        <dependency>
            <groupId>org.eclipse.kura</groupId>
            <artifactId>org.eclipse.kura.demo.heater</artifactId>
        </dependency>
    </dependencies>

    <!-- Change this if your org is different -->
    <organization>
        <name>Eclipse Kura</name>
        <url>https://eclipse.dev/kura/</url>
    </organization>

    <properties>
        <addon.installation.dir>/opt/eclipse/kura/plugins/6s</addon.installation.dir>
        <jar.name>kura-heater-example.bundle-${project.version}.jar</jar.name>
        <deb.architecture>all</deb.architecture>
        <package.name>kura-heater-example</package.name>
        <kura.repo.distribution>kura-6</kura.repo.distribution>
        <kura.repo.module>base</kura.repo.module>
        <summary>Eclipse Kura Addon for Heater</summary>
        <long.description>Examples of Heater addons for the Eclipse Kura Framework.</long.description>
    </properties>

    <profiles>
        <!-- Internal profile: FOR INTERNAL USE ONLY - active if -DreleaseBuild is *not* specified. -->
        <profile>
            <id>debugBuild</id>
            <activation>
                <property>
                    <name>!releaseBuild</name>
                </property>
            </activation>
            <properties>
                <maven.build.timestamp.format>yyyyMMddHHmm</maven.build.timestamp.format>
                <package.snapshot>git${maven.build.timestamp}.${git.commit.id.abbrev}</package.snapshot>

                <package.version>${release.version}~${package.snapshot}</package.version>
                <package.revision>1</package.revision>
            </properties>
        </profile>
        <!-- Internal profile: FOR INTERNAL USE ONLY - active if -DreleaseBuild *is* specified. -->
        <profile>
            <id>releaseBuild</id>
            <activation>
                <property>
                    <name>releaseBuild</name>
                </property>
            </activation>
            <properties>
                <package.version>${release.version}</package.version>
                <package.revision>1</package.revision>
            </properties>
        </profile>
    </profiles>

    <build>
        <plugins>
            <!-- Responsible for removing the "-SNAPSHOT" from the project.version -->
            <plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>build-helper-maven-plugin</artifactId>
                <version>3.6.0</version>
                <executions>
                    <execution>
                        <id>regex-property</id>
                        <goals>
                            <goal>regex-property</goal>
                        </goals>
                        <configuration>
                            <name>release.version</name>
                            <value>${project.version}</value>
                            <regex>-SNAPSHOT</regex>
                            <replacement></replacement>
                            <failIfNoMatch>false</failIfNoMatch>
                        </configuration>
                    </execution>
                </executions>
            </plugin>

            <!-- Responsible for retrieving the short git commit (defaults to length 7) -->
            <plugin>
                <groupId>io.github.git-commit-id</groupId>
                <artifactId>git-commit-id-maven-plugin</artifactId>
                <version>9.0.1</version>
                <executions>
                    <execution>
                        <id>get-the-git-infos</id>
                        <goals>
                            <goal>revision</goal>
                        </goals>
                        <phase>initialize</phase>
                    </execution>
                </executions>
                <configuration>
                    <injectAllReactorProjects>true</injectAllReactorProjects>
                    <generateGitPropertiesFile>false</generateGitPropertiesFile>
                    <skipPoms>false</skipPoms>
                    <includeOnlyProperties>
                        <includeOnlyProperty>^git.commit.id.abbrev$</includeOnlyProperty>
                    </includeOnlyProperties>
                </configuration>
            </plugin>

            <!-- Responsible for copying the dependencies into a known location -->
            <plugin>
                <artifactId>maven-dependency-plugin</artifactId>
                <executions>
                    <execution>
                        <id>get-bundles-to-distrib</id>
                        <phase>generate-resources</phase>
                        <goals>
                            <goal>copy-dependencies</goal>
                        </goals>
                        <configuration>
                            <excludeTypes>pom</excludeTypes>
                            <excludeClassifiers>sources</excludeClassifiers>
                            <excludeTransitive>true</excludeTransitive>
                            <outputDirectory>${project.build.directory}/plugins</outputDirectory>
                        </configuration>
                    </execution>
                </executions>
            </plugin>

            <plugin>
                <groupId>org.vafer</groupId>
                <artifactId>jdeb</artifactId>
                <version>1.12</version>
                <executions>
                    <execution>
                        <id>generate-deb</id>
                        <phase>package</phase>
                        <goals>
                            <goal>jdeb</goal>
                        </goals>
                        <configuration>
                            <verbose>true</verbose>
                            <deb>
                                ${basedir}/target/deb/${package.name}_${package.version}-${package.revision}_${deb.architecture}.deb</deb>
                            <snapshotExpand>true</snapshotExpand>
                            <snapshotTemplate>${package.snapshot}</snapshotTemplate>
                            <controlDir>${project.basedir}/deb/control</controlDir>
                            <skipPOMs>false</skipPOMs>
                            <dataSet>
                                <data>
                                    <src>${project.build.directory}/plugins</src>
                                    <type>directory</type>
                                    <mapper>
                                        <type>perm</type>
                                        <prefix>${addon.installation.dir}</prefix>
                                        <user>kurad</user>
                                        <group>kurad</group>
                                        <filemode>600</filemode>
                                    </mapper>
                                </data>
                            </dataSet>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>

    <distributionManagement>
        <repository>
            <id>repo.eclipse.org</id>
            <name>Kura Repository - Releases</name>
            <url>https://repo.eclipse.org/content/repositories/kura-releases/</url>
        </repository>
        <snapshotRepository>
            <id>repo.eclipse.org</id>
            <name>Kura Repository - Snapshots</name>
            <url>https://repo.eclipse.org/content/repositories/kura-snapshots/</url>
        </snapshotRepository>
    </distributionManagement>

</project>