<?xml version="1.0" encoding="UTF-8"?>
<!--

    Copyright (c) 2026 Eurotech and/or its affiliates and others

    This program and the accompanying materials are made
    available under the terms of the Eclipse Public License 2.0
    which is available at https://www.eclipse.org/legal/epl-2.0/

    SPDX-License-Identifier: EPL-2.0

    Contributors:
     Eurotech

-->
<project xmlns="http://maven.apache.org/POM/4.0.0"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">

    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>org.eclipse.kura</groupId>
        <artifactId>kura-examples-distrib</artifactId>
        <version>6.0.0-SNAPSHOT</version>
    </parent>

    <artifactId>kura-cloudcat-examples-distrib</artifactId>
    <packaging>pom</packaging>

    <dependencies>
        <dependency>
            <groupId>org.eclipse.kura</groupId>
            <artifactId>org.eclipse.kura.misc.cloudcat</artifactId>
        </dependency>
    </dependencies>

    <properties>
        <jar.name>kura-cloudcat-example.bundle-${project.version}.jar</jar.name>
        <package.name>kura-cloudcat-example</package.name>
        <summary>Eclipse Kura Addon for CloudCat</summary>
        <long.description>CloudService relay that republishes messages across cloud stacks for the
            Eclipse Kura Framework.</long.description>
    </properties>

    <build>
        <plugins>
            <plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>build-helper-maven-plugin</artifactId>
            </plugin>
            <plugin>
                <groupId>io.github.git-commit-id</groupId>
                <artifactId>git-commit-id-maven-plugin</artifactId>
            </plugin>
            <plugin>
                <artifactId>maven-dependency-plugin</artifactId>
            </plugin>
            <plugin>
                <groupId>org.vafer</groupId>
                <artifactId>jdeb</artifactId>
            </plugin>
        </plugins>
    </build>

</project>
