<?xml version="1.0" encoding="UTF-8"?>
<!--

    Copyright (c) 2025 Eurotech and/or its affiliates and others

    This program and the accompanying materials are made
    available under the terms of the Eclipse Public License 2.0
    which is available at https://www.eclipse.org/legal/epl-2.0/

    SPDX-License-Identifier: EPL-2.0

    Contributors:
     Eurotech

-->
<project xmlns="http://maven.apache.org/POM/4.0.0"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">

    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>org.eclipse.kura</groupId>
        <artifactId>kura-apps-distrib</artifactId>
        <version>6.0.0-SNAPSHOT</version>
        <relativePath>../pom.xml</relativePath>
    </parent>

    <artifactId>kura-examples-distrib</artifactId>
    <packaging>pom</packaging>

    <name>Kura Apps Examples Distribution</name>
    <description>Distribution packages for Kura Apps Examples</description>

    <modules>
        <module>ble</module>
        <module>camel</module>
        <module>container-validation</module>
        <module>gpio</module>
        <module>heater</module>
        <module>identity</module>
        <module>modbus</module>
        <module>publishers</module>
        <module>security</module>
        <module>sensehat</module>
        <module>wire-components</module>
    </modules>

    <repositories>
        <repository>
            <id>kura-releases</id>
            <name>Eclipse Kura Repository - Releases</name>
            <url>https://repo.eclipse.org/content/repositories/kura-releases/</url>
        </repository>
        <repository>
            <id>kura-snapshots</id>
            <name>Eclipse Kura Repository - Snapshots</name>
            <url>https://repo.eclipse.org/content/repositories/kura-snapshots/</url>
        </repository>
        <repository>
            <id>kura-addons</id>
            <name>Kura Addons Maven Repository</name>
            <url>https://raw.github.com/eurotech/kura_addons/mvn-repo/</url>
        </repository>
        <repository>
            <id>central</id>
            <url>https://repo1.maven.org/maven2/</url>
        </repository>
        <repository>
            <!-- moquette-broker -->
            <id>jitpack.io</id>
            <url>https://jitpack.io</url>
        </repository>
    </repositories>

    <profiles>
        <profile>
            <id>can</id>
            <activation>
                <property>
                    <name>enable.can.example</name>
                    <value>true</value>
                </property>
            </activation>
            <modules>
                <module>can</module>
            </modules>
        </profile>
    </profiles>
</project>